# axisJS config
---
framework: 'c3'

input: 'csv'

export:
  - 'WordPress'
  - 'Embed code'
  - 'pdf'

save:
  - 'png'
  - 'svg'

colors:
  - label: 'neutral 1'
    value: '#78B8DF'
  - label: 'neutral 2'
    value: '#AFCBCE'
  - label: 'neutral 3'
    value: '#23393D'
  - label: 'neutral 4'
    value: '#87AF9C'
  - label: 'yes'
    value: '#0EBF00'
  - label: 'no'
    value: '#ED1B24'
  - label: 'maybe'
    value: '#808080'
  - label: 'Labour'
    value: '#ED1B24'
  - label: 'Conservative'
    value: '#022397'
  - label: 'LibDem'
    value: '#FDBB30'
  - label: 'Ukip'
    value: '#722889'
  - label: 'Green'
    value: '#6AB023'
  - label: '#1f77b4' # begin c3.js defaults
    value: '#1f77b4'
  - label: '#aec7e8'
    value: '#aec7e8'
  - label: '#ff7f0e'
    value: '#ff7f0e'
  - label: '#ffbb78'
    value: '#ffbb78'
  - label: '#2ca02c'
    value: '#2ca02c'
  - label: '#98df8a'
    value: '#98df8a'
  - label: '#d62728'
    value: '#d62728'
  - label: '#ff9896'
    value: '#ff9896'
  - label: '#9467bd'
    value: '#9467bd'
  - label: '#c5b0d5'
    value: '#c5b0d5'
  - label: '#8c564b'
    value: '#8c564b'
  - label: '#c49c94'
    value: '#c49c94'
  - label: '#e377c2'
    value: '#e377c2'
  - label: '#f7b6d2'
    value: '#f7b6d2'
  - label: '#7f7f7f'
    value: '#7f7f7f'
  - label: '#c7c7c7'
    value: '#c7c7c7'
  - label: '#bcbd22'
    value: '#bcbd22'
  - label: '#dbdb8d'
    value: '#dbdb8d'
  - label: '#17becf'
    value: '#17becf'
  - label: '#9edae5'
    value: '#9edae5'

defaults:
  grid x: false
  grid y: false
  axis y: true
  axis y2: false
  axis x: true
  legend: true
  point: false
  y axis: 'y'

titles:
  title size: '32px'
  credit size: '30px'
  source size: '28px'
  source style: 'oblique'
  align: 'middle'

backgroundColor: 'white'

colorPicker: 'simple'
